### PR TITLE
Include link to professor's timetable in result entry

### LINKED ISSUE #17: Integrate with wimp
Add hyperlink of the search results to the corresponding page in WIMP. Related to https://github.com/themousepotato/wimp/issues/8

### PR DESCRIPTION
**Pull request by icyflame**
fixes #17

### CODE REVIEW

**Review by themousepotato — APPROVED** [review]

**Comment by icyflame** [comment]
Thanks for the review, @themousepotato. I will merge this tomorrow night, so everyone else has a chance to review these changes.

**Review by amrav — APPROVED** [review]
Looks fine with the caveat that if there's a small difference in spelling, then the link will return a 404. It would be nicer if wimp could run a search (and maybe redirect to the first result), but just a suggestion not a blocker.

**Comment by icyflame** [comment]
@amrav Yes, you are right. Perhaps we should move to a model similar to MFQP on WIMP, where entering a name starts a search in the list of professors and shows the results below and then clicking on any one opens their timetable.

Actually, this would be exactly the same as `mcmp` with a _very minor_ change to the JS script to use the code as is. @themousepotato it's your call, I don't have any particular preference either way.

**Comment by themousepotato** [comment]
On Saturday, September 8, 2018, Siddharth Kannan <notifications@github.com>
wrote:

> @amrav <https://github.com/amrav> Yes, you are right. Perhaps we should
> move to a model similar to MFQP on WIMP, where entering a name starts a
> search in the list of professors and shows the results below and then
> clicking on any one opens their timetable.
>
> Actually, this would be exactly the same as mcmp with a *very minor*
> change to the JS script to use the code as is. @themousepotato
> <https://github.com/themousepotato> it's your call, I don't have any
> particular preference either way.
>

There is an issue opened by @athityakumar on using fuzzy search. For the
time being I can use a simple Norvig’s spellcheck on the incorrect
spellings before throwing an error.  After all it’s midsems😅. I shall work
on this later. Thanks for the suggestion @amrav and thank you very much for
doing this @icyflame.

**Comment by icyflame** [comment]
@themousepotato I read up on the spell checker algorithm! Really interesting. If you don't have time, I can work on it! I have not worked with it before, so it will be fun. :slightly_smiling_face:

**Comment by themousepotato** [comment]
For sure @icyflame. We used this in Opensoft. Remember @athityakumar? :D



‌

On Sun, Sep 9, 2018 at 7:59 AM, Siddharth Kannan <notifications@github.com>
wrote:

> @themousepotato <https://github.com/themousepotato> I read up on the
> spell checker algorithm! Really interesting. If you don't have time, I can
> work on it! I have not worked with it before, so it will be fun. 🙂
>

And this is probably humbleness at it's peak @icyflame. :)

**Pull request merged**
