### PR TITLE
include department in the output list shown on MCMP

### LINKED ISSUE #14: Add professor department while searching
A friend of mine suggested we also show the department of the professor when displaying search results. 

This is helpful if a student wants to work within their department only.

Current search result:   `Sourangshu Bhattacharya | Machine Learning`

Suggested change:    `Sourangshu Bhattacharya | CS | Machine Learning`

I can take this up if the need for this is acknowledged by other folks.

### PR DESCRIPTION
**Pull request by icyflame**
fixes #14

### CODE REVIEW

**Comment by athityakumar** [comment]
@icyflame - Yup, the departments are shown now. Thanks for adding the custom mapping! 😄 

But looks like the issue I mentioned in #14 is much more prelevant due to our fuzzy-search. I think we could really use a dropdown for filtering by department(s). WDYT?

image

**Comment by icyflame** [comment]
@athityakumar I don't want to add a filter, it will make the UX bad. We should try to get everything inside this single text field. A good way to do that is to include the department in the fuzzy search and give it a higher weight while running the fuzzy search. We are not using fuzzy search, we are actually using [`string_score_min`](https://github.com/joshaven/string_score).

I included the department field in the search. After that, I got pretty good results:

1. Machine

image

2. Machine CS

image

3. Machine ME

image

These commits are now pushed.

**Comment by kaustubhhiware** [comment]
I would suggest let's stick to the single search bar without dropdowns. The screenshots suggest department filtering works perfectly. 
LGTM :+1:

**Review by kaustubhhiware — APPROVED** [review]
I would suggest let's stick to the single search bar without dropdowns. The screenshots suggest department filtering works perfectly.
LGTM :+1:

**Review by athityakumar — APPROVED** [review]

**Comment by athityakumar** [comment]
> A good way to do that is to include the department in the fuzzy search and give it a higher weight while running the fuzzy search.

Ah ofcourse, that'd be a better way. Good catch! I'm merging this now. 😄

**Pull request merged**
